/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as SkillsSkillIdRouteImport } from './routes/skills/$skillId'
import { Route as _authSignUpSplatRouteImport } from './routes/__auth/sign-up.$'
import { Route as _authSignInSplatRouteImport } from './routes/__auth/sign-in.$'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignUpSplatRoute = _authSignUpSplatRouteImport.update({
  id: '/__auth/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignInSplatRoute = _authSignInSplatRouteImport.update({
  id: '/__auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/saved': typeof SavedRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/sign-up/$': typeof _authSignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/saved': typeof SavedRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/sign-up/$': typeof _authSignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/saved': typeof SavedRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/__auth/sign-in/$': typeof _authSignInSplatRoute
  '/__auth/sign-up/$': typeof _authSignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registry'
    | '/saved'
    | '/skills/$skillId'
    | '/skills/new'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registry'
    | '/saved'
    | '/skills/$skillId'
    | '/skills/new'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/registry'
    | '/saved'
    | '/skills/$skillId'
    | '/skills/new'
    | '/__auth/sign-in/$'
    | '/__auth/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistryRoute: typeof RegistryRoute
  SavedRoute: typeof SavedRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsNewRoute: typeof SkillsNewRoute
  _authSignInSplatRoute: typeof _authSignInSplatRoute
  _authSignUpSplatRoute: typeof _authSignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/sign-up/$': {
      id: '/__auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof _authSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/sign-in/$': {
      id: '/__auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof _authSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryRoute: RegistryRoute,
  SavedRoute: SavedRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsNewRoute: SkillsNewRoute,
  _authSignInSplatRoute: _authSignInSplatRoute,
  _authSignUpSplatRoute: _authSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
